### ISSUE TITLE
improved: processView

### ISSUE THREAD

**Issue by tomasvanrijsse** [tomasvanrijsse/browser-quiz#26]
- [x] it should loop for 15 times, it should not care how much questions we have in total (we might end up with 100 questions in the data file)
- [x] `item.classList.add('disabled-bar');` can be easily moved to the foreach loop where we create the listitems. And using an if statement we could skip setting this class.
- [x] use a more descriptive variable name for `newDiv`

**Comment by brkzmn** [comment]
solved all issues
