### ISSUE TITLE
PlaySound 'wrong', why does is pause the right sound?

### ISSUE THREAD

**Issue by tomasvanrijsse** [tomasvanrijsse/browser-quiz#53]
The other two sounds seem really different from this last sound.
Why?

**Comment by viveriveniversum** [comment]
Because it overlaps. When wrong answer starts, correct sound should be muted.

**Comment by tomasvanrijsse** [comment]
But right and wrong sounds are never used for the same question right?
It's always waiting + wrong or waiting + right.
